[package]
name = "shape_of_light_x"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rs_ws281x = "0.4.2"
ctrlc = "3.2.1"
itertools = "0.10.1"